apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{- include "simple-crud.backend.name" . | nindent 4 }}
  labels:
    {{- include "simple-crud.labels" . | nindent 4 }}
    tier: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "simple-crud.selectorLabels" . | nindent 6 }}
      tier: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "simple-crud.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        tier: backend
    spec:
      serviceAccountName: simple-crud
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: "{{ .Chart.Name }}-init"
          image: "groundnuty/k8s-wait-for:1.3"
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          args:
            - "job"
            - "{{ .Values.job.name }}"
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.container.repository }}:{{ .Values.backend.container.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.container.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.postgresql.configmap.name }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-creds-secret
                  key: password
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
