apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresql.configmap.name }}
data:
  POSTGRES_SVC: {{quote .Values.postgresql.fullnameOverride }}
  POSTGRES_PORT: {{quote .Values.postgresql.containerPorts.postgresql }}
  POSTGRES_DB: {{quote .Values.postgresql.auth.database }}