apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-crud.ui.name" . }}
  labels:
    {{- include "simple-crud.labels" . | nindent 4 }}
    tier: ui
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.ui.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "simple-crud.selectorLabels" . | nindent 4 }}
    tier: ui
