spring:
  jpa:
    database: postgresql
  datasource:
    url: jdbc:postgresql://${POSTGRES_SVC}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
openapi:
  otusSimpleCrud:
    base-path: /
server:
  port: 8000
  servlet:
    context-path: /simple-crud
