backend:
  name: simple-crud-backend
  replicaCount: 2
  container:
    repository: glebegunov/simple-crud
    pullPolicy: IfNotPresent
    tag: "0.1.9"
  service:
    type: ClusterIP
    port: 8000

ui:
  replicaCount: 1
  name: simple-crud-ui
  container:
    repository: glebegunov/crud-ui
    pullPolicy: Never
    tag: "0.0.3"
  service:
    type: ClusterIP
    port: 3000

gateway:
  replicaCount: 1
  name: simple-crud-gateway
  container:
    repository: glebegunov/backend-gateway
    pullPolicy: Never
    tag: 0.0.7
  service:
    type: ClusterIP
    port: 8080

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}


ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

livenessProbe:
  httpGet:
    path: /api/actuator/health
    port: 8000
  initialDelaySeconds: 60

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []

job:
  name: simple-crud-migration-job
  restartPolicy: Never
  image:
    repository: glebegunov/simple-crud-migration
    tag: 0.0.6

postgresql:
  fullnameOverride: simple-crud-postgresql
  auth:
    database: postgres
    username: postgres
    postgresPassword: qwerty
  # Values for the deployment of the configmap for the postgresql
  configmap:
    name: postgres-configmap