scrape_configs:
  - job_name: 'simple_crud_in_k8s'
    metrics_path: '/simple-crud/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['simple-crud:80']
  - job_name: 'nginx'
    metrics_path: '/metrics'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['nginx-ingress-nginx-controller-metrics:10254']